{
 "title": "Opstree/Node Exporter A",
 "description": "Grafana Dashboard for Host Level Metrics using Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info, instance)"
   },
   {
    "name": "job",
    "label": "Category",
    "query": "label_values(node_uname_info, job)"
   },
   { "name": "hostname", "label": "Hostname" },
   {
    "name": "device",
    "label": "device",
    "query": "label_values(node_disk_reads_completed_total, device)"
   },
   {
    "name": "devices",
    "query": "label_values(node_filesystem_size_bytes, device)"
   },
   { "name": "maxmount", "label": "maxmount" },
   {
    "name": "total",
    "label": "total_servers",
    "query": "query_result(count(node_uname_info{job=~\"$job\"}))"
   },
   {
    "name": "network_interface",
    "label": "network_interface",
    "query": "label_values(node_network_info{operstate=\"up\"}, device)"
   }
  ]
 },
 "panels": [
  { "title": "Historical Mertics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$instance\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "System "
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=\"$instance\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=\"$instance\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Nice"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$instance\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Iowait"
    }
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Sys Load avg",
   "type": "stat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$instance\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))",
     "legendFormat": "1 min"
    },
    {
     "expr": "avg(node_load5{instance=\"$instance\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu)) ",
     "legendFormat": "5 min"
    },
    {
     "expr": "avg(node_load15{instance=\"$instance\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu)) ",
     "legendFormat": "15 min"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$instance\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$instance\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$instan\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "RAM info",
   "type": "stat",
   "description": "Node Memory info",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(node_memory_MemTotal_bytes{instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Total GB"
    },
    {
     "expr": "ceil(node_memory_MemFree_bytes{instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Available GB"
    },
    {
     "expr": "(ceil(node_memory_MemTotal_bytes{instance=\"$instance\"}/(1024*1024))/1024)-(ceil(node_memory_MemFree_bytes{instance=\"$instance\"})/(1024*1024))/1024",
     "legendFormat": "Used GB"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$instance\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "ROOT FILESYSTEM",
   "type": "stat",
   "description": "device=\"/dev/root\n",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(node_filesystem_size_bytes{device=\"/dev/root\",instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Total GB"
    },
    {
     "expr": "ceil(node_filesystem_avail_bytes{device=\"/dev/root\",instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Available GB"
    },
    {
     "expr": "ceil(node_filesystem_size_bytes{device=\"/dev/root\",instance=\"$instance\"}/(1024*1024))/1024-ceil(node_filesystem_avail_bytes{device=\"/dev/root\",instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Used GB"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Network received and transmit",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}}  receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{ instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  { "title": "Current metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$instance\",job=\"$job\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Root FS Used"
    }
   ]
  },
  {
   "title": "Network Traffic Out",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=\"$network_interface\",instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Network Traffic In",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"$network_interface\",instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Free inodes:$maxmount ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{instance=~\"$instance\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "Disk Space Used ",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  }
 ]
}