{
 "title": "ZooKeeper",
 "description": "ZooKeeper Dashboard for Prometheus metrics scraper",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "host", "label": "Host", "query": "label_values(host)" },
   { "name": "port", "label": "Port", "query": "label_values(instance)" },
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_znode_count{instance= \"$instance\"}",
     "legendFormat": "{{instance}} znode_count"
    }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_packets_received", "legendFormat": "{{instance}} packets_received" }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_approximate_data_size",
     "legendFormat": "{{instance}} approximate_data_size"
    }
   ]
  },
  {
   "title": "outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_outstanding_requests",
     "legendFormat": "{{instance}} outstanding_requests"
    }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_packets_sent", "legendFormat": "{{instance}} packets_sent" }
   ]
  },
  { "title": "disk/snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "file_descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "open_file_descriptor_count", "legendFormat": "open_file_descriptor_count" },
    { "expr": "process_max_fds", "legendFormat": "process_max_fds" }
   ]
  },
  { "title": "latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "max_min_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_max_latency", "legendFormat": "{{instance}} max_latency" },
    { "expr": "zookeeper_max_latency", "legendFormat": "{{instance}} min_latency" },
    { "expr": "avg_latency", "legendFormat": "{{instance}} avg_latency" }
   ]
  },
  {
   "title": "avg_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_avg_latency", "legendFormat": "{{instance}} avg_latency" }
   ]
  }
 ]
}