{
 "title": "Opstree/Elasticsearch Dashboard ",
 "description": "Display Elasticsearch metrics",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "elasticsearch_cluster_health_status{}"
    }
   },
   {
    "name": "job",
    "label": "Cluster-name",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{job=\"$job\", cluster=\"$cluster\", name!=\"\"},instance)"
    }
   },
   {
    "name": "shard_type",
    "label": "Shard Type",
    "query": {
     "query": "label_values(es_cluster_shards_number, type)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster status - Green",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{color=\"green\"})"
      }
     ]
    },
    {
     "title": "Cluster status - Yellow",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{color=\"yellow\"})"
      }
     ]
    },
    {
     "title": "Cluster status - Red",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{color=\"red\"})"
      }
     ]
    },
    {
     "title": "Open file descriptors per cluster",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (elasticsearch_process_open_files_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Data nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 2, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Active primary shards",
     "type": "stat",
     "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 4 },
     "repeat": "shard_type",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_active_primary_shards{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Active shards",
     "type": "stat",
     "description": "Aggregate total of all shards across all indices, which includes replica shards",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_active_shards{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Delayed shards",
     "type": "stat",
     "description": "Shards delayed to reduce reallocation overhead",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"} "
      }
     ]
    },
    {
     "title": "Initializing shards",
     "type": "stat",
     "description": "Count of shards that are being freshly created",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_initializing_shards{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Relocating shards",
     "type": "stat",
     "description": "The number of shards that are currently moving from one node to another node.",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_relocating_shards{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Pending tasks",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "elasticsearch_process_cpu_percent{cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{ instance=~'$host', job='node_exporter' }-(node_memory_MemFree_bytes{ instance=~'$host', job='node_exporter' } + node_memory_Cached_bytes{ instance=~'$host', job='node_exporter' } + node_memory_Buffers_bytes{ instance=~'$host', job='node_exporter' }) )/node_memory_MemTotal_bytes{ instance=~'$host', job='node_exporter' })*100",
       "legendFormat": "{{ area }} - {{ instance }}"
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",instance=~\"$instance\"} / elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",instance=~\"$instance\"})*100",
       "legendFormat": "{{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM memory used Avg.",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (elasticsearch_jvm_memory_used_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}) / sum (elasticsearch_jvm_memory_max_bytes{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}) * 100"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes", "label": "Heap" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{area}}-{{instance }} "
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{gc}} - {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Documents and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_search_query_time_seconds{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[1m]) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Search rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "Searches/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Documents count (with replicas)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Documents" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_docs{cluster=\"$cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Documents deleting rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_docs_deleted{cluster=\"$cluster\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Indexing latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\", instance=~\"$instance\"}[1m]) / irate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\", instance=~\"$instance\"}[1m]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Search latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\", instance=~\"$instance\"}[1m]) / rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Document Indexing time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indexing throttling",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_store_throttle_time_seconds_total{cluster=\"$cluster\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Document Merging time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "{{name}} - {{gc}}"
      }
     ]
    },
    {
     "title": "Load average",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_os_load1{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "load1: {{name}}"
      },
      {
       "expr": "elasticsearch_os_load5{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "load5: {{name}}"
      },
      {
       "expr": "elasticsearch_os_load15{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "load15: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool operations completed",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_thread_pool_completed_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool threads active",
     "type": "graph",
     "gridPos": { "h": 12, "w": 6, "x": 7, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_thread_pool_active_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool operations queued",
     "type": "graph",
     "gridPos": { "h": 12, "w": 6, "x": 13, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_thread_pool_active_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool operations rejected",
     "type": "graph",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_thread_pool_rejected_count{job=\"$job\",instance=~\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    }
   ]
  }
 ]
}