{
 "title": "System Information",
 "description": "System Information Dashboard provides information about the node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(system_uptime, instance)"
   },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{instance=~ \"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{instance=~ \"$instance$\",path = '/'}"
    }
   ]
  },
  {
   "title": "Top CPU Consuming Process",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1,procstat_cpu_usage{instance=~\"$instance\"})",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mem_used{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last 1 min System Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "system_load1{instance=~ \"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Memory Consumption Process",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5,procstat_memory_usage{instance=~\"$instance\"})",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (cpu_usage_idle{instance=~ \"$instance*\",cpu=\"cpu-total\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (cpu_usage_idle{instance=~ \"$instance*\",cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{instance=~\"$instance*\"}",
     "legendFormat": "mem_used"
    },
    {
     "expr": "(mem_buffered{instance=~\"$instance\"}/mem_total{instance=~\"$instance\"})*100",
     "legendFormat": "mem_buffered"
    },
    {
     "expr": "(mem_cached{instance=~\"$instance\"}/mem_total{instance=~\"$instance\"})*100",
     "legendFormat": "mem_cached"
    },
    {
     "expr": "(swap_used{instance=~\"$instance\"}/mem_total{instance=~\"$instance\"})*100",
     "legendFormat": "mem_swap"
    }
   ]
  },
  {
   "title": "Disks Usages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{instance=~\"$instance\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk IO Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "diskio_write_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk IO Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "diskio_read_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}