{
 "title": "Mongo DB",
 "description": "Should display mongodb overview for telegraf 1.5",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "env", "query": "label_values(env)" },
   {
    "name": "host",
    "query": "label_values(mongodb_inserts_per_sec{env=\"$env\"},host)"
   },
   { "name": "inter", "label": "Interval", "query": "1m,10m,30m,1h,6h" }
  ]
 },
 "panels": [
  {
   "title": "DB Uptime",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(mongodb_uptime_ns{host=~ \"$host\"}*10^-9)/3600",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Current master",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "mongodb_inserts_per_sec{state=\"PRIMARY\", env=\"$env\"}"
    }
   ]
  },
  {
   "title": "mongo operations $host",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 4 },
   "repeat": "host",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "commands_per_sec $tag_host",
     "expr": "mongodb_inserts_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inserts ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"commands_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "commands_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "deletes_per_sec $tag_host",
     "expr": "mongodb_queries_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Queries ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"deletes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "deletes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "flushes_per_sec $tag_host",
     "expr": "mongodb_updates_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Updates",
     "measurement": "mongodb",
     "query": "SELECT mean(\"flushes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "flushes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "getmores_per_sec $tag_host",
     "expr": "mongodb_commands_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Commands",
     "measurement": "mongodb",
     "query": "SELECT mean(\"getmores_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "getmores_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "inserts_per_sec $tag_host",
     "expr": "mongodb_flushes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Flushes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"inserts_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "inserts_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "queries_per_sec $tag_host",
     "expr": "mongodb_getmores_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Getmores",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "queries_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "updates_per_sec $tag_host",
     "expr": "mongodb_deletes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deletes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "updates_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "mongo operations $host",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "commands_per_sec $tag_host",
     "expr": "mongodb_inserts_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inserts ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"commands_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "commands_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "deletes_per_sec $tag_host",
     "expr": "mongodb_queries_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Queries ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"deletes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "deletes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "flushes_per_sec $tag_host",
     "expr": "mongodb_updates_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Updates",
     "measurement": "mongodb",
     "query": "SELECT mean(\"flushes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "flushes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "getmores_per_sec $tag_host",
     "expr": "mongodb_commands_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Commands",
     "measurement": "mongodb",
     "query": "SELECT mean(\"getmores_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "getmores_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "inserts_per_sec $tag_host",
     "expr": "mongodb_flushes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Flushes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"inserts_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "inserts_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "queries_per_sec $tag_host",
     "expr": "mongodb_getmores_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Getmores",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "queries_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "updates_per_sec $tag_host",
     "expr": "mongodb_deletes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deletes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "updates_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "mongo operations $host",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "commands_per_sec $tag_host",
     "expr": "mongodb_inserts_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inserts ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"commands_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "commands_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "deletes_per_sec $tag_host",
     "expr": "mongodb_queries_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Queries ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"deletes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "deletes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "flushes_per_sec $tag_host",
     "expr": "mongodb_updates_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Updates",
     "measurement": "mongodb",
     "query": "SELECT mean(\"flushes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "flushes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "getmores_per_sec $tag_host",
     "expr": "mongodb_commands_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Commands",
     "measurement": "mongodb",
     "query": "SELECT mean(\"getmores_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "getmores_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "inserts_per_sec $tag_host",
     "expr": "mongodb_flushes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Flushes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"inserts_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "inserts_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "queries_per_sec $tag_host",
     "expr": "mongodb_getmores_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Getmores",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "queries_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "updates_per_sec $tag_host",
     "expr": "mongodb_deletes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deletes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "updates_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_active_reads{env=\"$env\",host=~\"$host\"}",
     "legendFormat": "Reads: {{host}}"
    }
   ]
  },
  {
   "title": "Current Writes Queue to Master",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_active_writes{env=\"$env\", state=\"PRIMARY\"}"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_open_connections{env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Updates per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_updates_per_sec{host=~\"$host\"}",
     "legendFormat": "updates"
    }
   ]
  },
  {
   "title": "Insert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_inserts_per_sec{host=~ \"$host\"}",
     "legendFormat": "Insert"
    }
   ]
  },
  {
   "title": "Delete per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_deletes_per_sec{host=~\"$host\"}",
     "legendFormat": "deletes/sec"
    }
   ]
  }
 ]
}