{
 "title": "Apache2",
 "description": "Apache Web Server Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(system_uptime, instance)"
   },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Apache2 Requests Status Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Response 2XX / 5m",
   "type": "graph",
   "description": "Requests with 200 Status Code",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(apache2log_resp_bytes{instance=~\"$instance*\",resp_code=~\"200\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Total Response 200 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 200 response by Apache2 server",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(apache2log_resp_bytes{instance=~\"$instance*\", resp_code=~\"200\"}[24h])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Response 4XX  /5m",
   "type": "graph",
   "description": "Requests with 4XX Status Code",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(apache2log_http_version{instance=~\"$instance*\", resp_code=~\"40.\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Total Response 404 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 404 response from Apache2 server",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(apache2log_http_version{instance=~\"$instance*\", resp_code=~\"404\"}[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (cpu_usage_idle{instance=~ \"$instance*\",cpu=\"cpu-total\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current CPU Utilization %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (cpu_usage_idle{instance=~ \"$instance*\",cpu=\"cpu-total\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mem_used{instance=~\"$instance\"})",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "rate(net_bytes_recv[5m])", "legendFormat": "net_bytes_recv" },
    {
     "expr": "rate(net_conntrack_listener_conn_accepted_total[5m])",
     "legendFormat": "net_conn_accepted"
    }
   ]
  },
  {
   "title": "Network Ouput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "rate(net_bytes_sent[5m])", "legendFormat": "net_bytes_sent" },
    {
     "expr": "rate(net_conntrack_listener_conn_accepted_total[5m])",
     "legendFormat": "net_conn_accepted"
    }
   ]
  },
  {
   "title": "Apache2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "apache Uptime/serverUptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "apache_Uptime{instance=~\"$instance\"}",
       "legendFormat": "apache_Uptime"
      },
      {
       "expr": "apache_ServerUptimeSeconds{instance=~\"$instance\"}",
       "legendFormat": "apache_ServerUptimeSeconds"
      }
     ]
    },
    {
     "title": "Current total apache accesses",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(apache_TotalAccesses{instance=~ \"$instance\"}[5m])\t",
       "legendFormat": "Accesses"
      }
     ]
    },
    {
     "title": "Apache CPU load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "apache_CPULoad{instance=~ \"$instance\"}",
       "legendFormat": "CPULoad"
      },
      {
       "expr": "apache_CPUSystem{instance=~ \"$instance\"}",
       "legendFormat": "CPUSystem"
      },
      {
       "expr": "apache_CPUUser{instance=~ \"$instance\"}",
       "legendFormat": "CPUUser"
      }
     ]
    },
    {
     "title": "Apache scoreboard statuses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "apache_scboard_closing{instance=~ \"$instance\"}",
       "legendFormat": "closing"
      },
      {
       "expr": "apache_scboard_dnslookup{instance=~ \"$instance\"}",
       "legendFormat": "dns"
      },
      {
       "expr": "apache_scboard_finishing{instance=~ \"$instance\"}",
       "legendFormat": "finishing"
      },
      {
       "expr": "apache_scboard_idle_cleanup{instance=~ \"$instance\"}",
       "legendFormat": "idle_cleanup"
      },
      {
       "expr": "apache_scboard_keepalive{instance=~ \"$instance\"}",
       "legendFormat": "keep alive"
      },
      {
       "expr": "apache_scboard_logging{instance=~ \"$instance\"}",
       "legendFormat": "logging"
      },
      {
       "expr": "apache_scboard_open{instance=~ \"$instance\"}",
       "legendFormat": "open_slot"
      },
      {
       "expr": "apache_scboard_reading{instance=~ \"$instance\"}",
       "legendFormat": "read"
      },
      {
       "expr": "apache_scboard_sending{instance=~ \"$instance\"}",
       "legendFormat": "send"
      },
      {
       "expr": "apache_scboard_starting{instance=~ \"$instance\"}",
       "legendFormat": "startup"
      },
      {
       "expr": "apache_scboard_waiting{instance=~ \"$instance\"}",
       "legendFormat": "wait"
      }
     ]
    },
    {
     "title": "Apache worker statuses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "apache_BusyWorkers{instance=~ \"$instance\"}",
       "legendFormat": "Busy"
      },
      {
       "expr": "apache_IdleWorkers{instance=~ \"$instance\"}",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "apache_Bytes sent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "apache_BytesPerReq{instance=~ \"$instance\"}",
       "legendFormat": "BytesPerReq"
      },
      {
       "expr": "apache_BytesPerSec{instance=~ \"$instance\"}",
       "legendFormat": "BytesPerSec"
      },
      {
       "expr": "apache_TotalkBytes{instance=~ \"$instance\"}",
       "legendFormat": "TotalkBytes"
      }
     ]
    }
   ]
  }
 ]
}