{
 "title": "Cassandra",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datacenter", "query": "prometheus" },
   {
    "name": "host",
    "query": "label_values(cassandraClient_connectedNativeClients_Value, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Genral Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Native Clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cassandraClient_connectedNativeClients_Value{instance=\"$host\"}"
    }
   ]
  },
  { "title": "Java Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Java Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "javaMemory_HeapMemoryUsage_committed{instance=\"$host\"}",
     "legendFormat": "java_heap_committed"
    },
    {
     "expr": "javaMemory_HeapMemoryUsage_init{instance=\"$host\"}",
     "legendFormat": "java_heap_init"
    },
    {
     "expr": "javaMemory_HeapMemoryUsage_max{instance=\"$host\"}",
     "legendFormat": "java_heap_max"
    },
    {
     "expr": "javaMemory_HeapMemoryUsage_used{instance=\"$host\"}",
     "legendFormat": "java_heap_used"
    }
   ]
  },
  {
   "title": "Java Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "javaMemory_NonHeapMemoryUsage_committed{instance=\"$host\"}",
     "legendFormat": "java_nonheap_committed"
    },
    {
     "expr": "javaMemory_NonHeapMemoryUsage_init{instance=\"$host\"}",
     "legendFormat": "java_nonheap_init"
    },
    {
     "expr": "javaMemory_NonHeapMemoryUsage_max{instance=\"$host\"}",
     "legendFormat": "java_nonheap_max"
    },
    {
     "expr": "javaMemory_NonHeapMemoryUsage_used{instance=\"$host\"}",
     "legendFormat": "java_nonheap_used"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "javaGarbageCollector_CollectionCount{instance=~\"$host\",mname=\"ConcurrentMarkSweep\"}",
     "legendFormat": "gc_ConcurrentMarkSweep"
    },
    {
     "expr": "javaGarbageCollector_CollectionCount{instance=~\"$host\",mname=\"ParNew\"}",
     "legendFormat": "gc_ParNew"
    }
   ]
  },
  { "title": "Cassandra Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Client Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandraClientRequest_Latency_Count{instance=\"$host\",scope=\"Read\"}",
     "legendFormat": "read_latency_count"
    },
    {
     "expr": "cassandraClientRequest_Latency_Min{instance=\"$host\",scope=\"Read\"}",
     "legendFormat": "read_latency_min"
    },
    {
     "expr": "cassandraClientRequest_Latency_Max{instance=\"$host\",scope=\"Read\"}",
     "legendFormat": "read_latency_max"
    }
   ]
  },
  {
   "title": "Client Write  Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandraClientRequest_Latency_Count{instance=\"$host\",scope=\"Write\"}",
     "legendFormat": "write_latency_count"
    },
    {
     "expr": "cassandraClientRequest_Latency_Max{instance=\"$host\",scope=\"Write\"}",
     "legendFormat": "write_latency_max"
    },
    {
     "expr": "cassandraClientRequest_Latency_Min{instance=\"$host\",scope=\"Write\"}",
     "legendFormat": "write_latency_min"
    }
   ]
  },
  {
   "title": "Table WriteLatency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandraTable_WriteLatency_Count{instance=\"$host\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Table ReadLatency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandraTable_ReadLatency_Count{instance=\"$host\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "LiveDiskSpaceUsed",
   "type": "graph",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandraTable_LiveDiskSpaceUsed_Count{instance=\"$host\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Disk IO Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diskio_write_bytes{instance=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk IO Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(diskio_read_bytes[5m])", "legendFormat": "{{name}}" },
    {}
   ]
  },
  {
   "title": "Cache Hits / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandraCache_Hits_Count{instance=\"$host\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Thread Pool Active & Pending Taks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandraThreadPools_ActiveTasks_Value{instance=\"$host\"}",
     "legendFormat": "active_tasks_{{scope}}"
    },
    {
     "expr": "cassandraThreadPools_PendingTasks_Value{instance=\"$host\"}",
     "legendFormat": "pending_tasks_{{scope}}"
    }
   ]
  },
  {
   "title": "Commit Logs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandraCommitLog_TotalCommitLogSize_Value{instance=\"$host\"}",
     "legendFormat": "{{mname}}"
    },
    {
     "expr": "cassandraCommitLog_PendingTasks_Value{instance=\"$host\"}",
     "legendFormat": "{{mname}}"
    }
   ]
  }
 ]
}