{
 "title": "Opstree/Nginx",
 "description": "Grafana Dashboard for Nginx Web Server.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" },
   { "name": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "job",
    "label": "Category",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU% Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"system\"}[$interval])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"user\"}[$interval])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"iowait\"}[$interval])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"idle\"}[$interval])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU Core",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Sys Load avg",
     "type": "stat",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load1{instance=~\"$instance\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$instance\",job=\"$job\"}) by (cpu))"
      },
      {
       "expr": "avg(node_load5{instance=~\"$instance\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$instance\",job=\"$job\"}) by (cpu)) "
      },
      {
       "expr": "avg(node_load15{instance=~\"$instance\",job=\"$job\"}) / count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu)) "
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$instance\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$instance\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$instan\",job=\"$job\"})"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$instance\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$instance\",job=\"$job\"}"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$instance\",job=\"$job\"}"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$instance\",job=\"$job\"})"
      }
     ]
    },
    {
     "title": "RAM info",
     "type": "stat",
     "description": "Node Memory info",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceil(node_memory_MemTotal_bytes{instance=~\"$instance\"}/(1024*1024))/1024"
      },
      {
       "expr": "ceil(node_memory_MemFree_bytes{instance=~\"$instance\"}/(1024*1024))/1024"
      },
      {
       "expr": "(ceil(node_memory_MemTotal_bytes{instance=~\"$instance\"}/(1024*1024))/1024)-(ceil(node_memory_MemFree_bytes{instance=~\"$instance\"})/(1024*1024))/1024"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$instance\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$instance\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "ROOT FILESYSTEM",
     "type": "stat",
     "description": "device=\"/dev/root\n",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceil(node_filesystem_size_bytes{instance=\"$instance\"}/(1024*1024))/1024",
       "legendFormat": "Total GB"
      },
      {
       "expr": "ceil(node_filesystem_avail_bytes{instance=\"$instance\"}/(1024*1024))/1024",
       "legendFormat": "Available GB"
      },
      {
       "expr": "ceil(node_filesystem_size_bytes{instance=\"$instance\"}/(1024*1024))/1024-ceil(node_filesystem_avail_bytes{instance=\"$instance\"}/(1024*1024))/1024",
       "legendFormat": "Used GB"
      }
     ]
    },
    {
     "title": "Network Input",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "rate(net_bytes_recv[5m])", "legendFormat": "net_bytes_recv" },
      {
       "expr": "rate(net_conntrack_listener_conn_accepted_total[5m])",
       "legendFormat": "net_conn_accepted"
      }
     ]
    },
    {
     "title": "Network Ouput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "rate(net_bytes_sent[5m])", "legendFormat": "net_bytes_sent" },
      {
       "expr": "rate(net_conntrack_listener_conn_accepted_total[5m])",
       "legendFormat": "net_conn_accepted"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx Requests Status Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response 2XX / 5m",
     "type": "graph",
     "description": "Requests with 200 Status Code",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(nginx_http_requests_total{instance=~\"$instance*\", status=~\"20.\"}[5m])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Response 200 Req. [24h]",
     "type": "bargauge",
     "description": "Total number of request in 24 hours for 200 response by nginx server",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum_over_time(nginx_http_requests_total{instance=~\"$instance*\", status=~\"200\"}[24h])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Response 4XX  /5m",
     "type": "graph",
     "description": "Requests with 4XX Status Code",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(nginx_http_requests_total{instance=~\"$instance*\", status=~\"40.\"}[5m])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Response 4xx Req. [24h]",
     "type": "bargauge",
     "description": "Total number of request in 24 hours for 404 response from nginx server",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum_over_time(nginx_http_requests_total{instance=~\"$instance*\", status=~\"40.\"}[24m])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Response 3XX",
     "type": "graph",
     "description": "Requests with 3XX Status Code",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(nginx_http_requests_total{instance=~\"$instance*\", status=~\"30.\"}[5m])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Response 5XX",
     "type": "graph",
     "description": "Requests with 5XX Status Code",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(nginx_http_requests_total{instance=~\"$instance*\", status=~\"50.\"}[5m])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Request 503 Resonse",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum_over_time(nginx_http_requests_total{instance=~\"$instance*\", status=~\"503\"}[5m])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Each Request Detail",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "nginx_http_requests_total{instance=~\"$instance*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx_Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx_http_request_count",
     "type": "graph",
     "description": "The total number of accepted connections from clients since the nginx master process started. Note that reloading configurations or restarting worker processes will not reset this metric. If you terminate and restart the master process, you will reset the metric.\n\n",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_http_request_duration_seconds_count{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "nginx_http_request_sum",
     "type": "bargauge",
     "description": "The current number of active (accepted) connections from clients. Includes all connections with the statuses Idle / Waiting, Reading, and Writing.",
     "gridPos": { "h": 11, "w": 11, "x": 13, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "nginx_http_request_duration_seconds_sum{instance=~\"$instance\"}",
       "legendFormat": "{{instance }}"
      }
     ]
    },
    {
     "title": "Nginx Writing",
     "type": "stat",
     "description": "The current number of connections from clients where nginx is writing a response back to the client.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "nginx_http_connections{instance=~\"$instance\",state=\"writing\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "nginx_reading",
     "type": "stat",
     "description": "The current number of (accepted) connections from clients where nginx is reading the request. Measured at the time the status module was queried.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "nginx_http_connections{instance=~\"$instance\",state=\"reading\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Nginx Waiting Connections",
     "type": "stat",
     "description": "The current number of connections from clients that are in the Idle / Waiting state.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "nginx_http_connections{instance=~\"$instance\",state=\"waiting\"}",
       "legendFormat": "{{ state}}"
      }
     ]
    },
    {
     "title": "nginx_http_request_duration_seconds_bucket",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_http_request_duration_seconds_bucket{instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx_total_errors_metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "nginx_metric_errors_total",
     "type": "stat",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nginx_metric_errors_total{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}